// Device type           -- in the "User Defined" range."
#define IOCTL_TYPE 40000

// The IOCTL function codes from 0x800 to 0xFFF are for customer use.
#define IOCTL_METHOD_IN_DIRECT CTL_CODE( IOCTL_TYPE, 0x900, METHOD_IN_DIRECT, FILE_ANY_ACCESS  )
#define IOCTL_METHOD_OUT_DIRECT CTL_CODE( IOCTL_TYPE, 0x901, METHOD_OUT_DIRECT , FILE_ANY_ACCESS  )
#define IOCTL_METHOD_BUFFERED CTL_CODE( IOCTL_TYPE, 0x902, METHOD_BUFFERED, FILE_ANY_ACCESS  )
#define IOCTL_METHOD_IN_NEITHER CTL_CODE( IOCTL_TYPE, 0x903, METHOD_NEITHER, FILE_ANY_ACCESS  )
#define IOCTL_METHOD_OUT_NEITHER CTL_CODE( IOCTL_TYPE, 0x904, METHOD_NEITHER, FILE_ANY_ACCESS  )
#define IOCTL_MMAP CTL_CODE( IOCTL_TYPE, 0x905, METHOD_OUT_DIRECT, FILE_ANY_ACCESS  )
#define IOCTL_TEST_WRITTEN_DATA CTL_CODE( IOCTL_TYPE, 0x950, METHOD_BUFFERED, FILE_ANY_ACCESS  )

#define DRIVER_FUNC_INSTALL     0x01
#define DRIVER_FUNC_REMOVE      0x02

#define DRIVER_NAME       "NetMap"

#define NT_DEVICE_NAME      L"\\Device\\NETMAP"
#define DOS_DEVICE_NAME     L"\\DosDevices\\NetMap"

typedef struct _MEMORY_ENTRY
{
    PVOID       pBuffer;         
} MEMORY_ENTRY, *PMEMORY_ENTRY;
